/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gameproto.v1.LookAroundAnswer');

goog.require('jspb.Message');
goog.require('proto.gameproto.v1.Object');

goog.forwardDeclare('proto.gameproto.v1.Types');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gameproto.v1.LookAroundAnswer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gameproto.v1.LookAroundAnswer.repeatedFields_, null);
};
goog.inherits(proto.gameproto.v1.LookAroundAnswer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gameproto.v1.LookAroundAnswer.displayName = 'proto.gameproto.v1.LookAroundAnswer';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gameproto.v1.LookAroundAnswer.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gameproto.v1.LookAroundAnswer.prototype.toObject = function(opt_includeInstance) {
  return proto.gameproto.v1.LookAroundAnswer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gameproto.v1.LookAroundAnswer} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gameproto.v1.LookAroundAnswer.toObject = function(includeInstance, msg) {
  var f, obj = {
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.gameproto.v1.Object.toObject, includeInstance),
    type: msg.getType()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.gameproto.v1.LookAroundAnswer} The clone.
 */
proto.gameproto.v1.LookAroundAnswer.prototype.cloneMessage = function() {
  return /** @type {!proto.gameproto.v1.LookAroundAnswer} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Object results = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.gameproto.v1.Object>}
 */
proto.gameproto.v1.LookAroundAnswer.prototype.getResultsList = function() {
  return /** @type{!Array.<!proto.gameproto.v1.Object>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gameproto.v1.Object, 1));
};


/** @param {Array.<!proto.gameproto.v1.Object>} value  */
proto.gameproto.v1.LookAroundAnswer.prototype.setResultsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.gameproto.v1.LookAroundAnswer.prototype.clearResultsList = function() {
  this.setResultsList([]);
};


/**
 * optional Types type = 2;
 * @return {!proto.gameproto.v1.Types}
 */
proto.gameproto.v1.LookAroundAnswer.prototype.getType = function() {
  return /** @type {!proto.gameproto.v1.Types} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {!proto.gameproto.v1.Types} value  */
proto.gameproto.v1.LookAroundAnswer.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};


