// source: game.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gameproto.v1.LookAroundAnswer');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.gameproto.v1.Object');

goog.forwardDeclare('proto.gameproto.v1.Types');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gameproto.v1.LookAroundAnswer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gameproto.v1.LookAroundAnswer.repeatedFields_, null);
};
goog.inherits(proto.gameproto.v1.LookAroundAnswer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gameproto.v1.LookAroundAnswer.displayName = 'proto.gameproto.v1.LookAroundAnswer';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gameproto.v1.LookAroundAnswer.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gameproto.v1.LookAroundAnswer.prototype.toObject = function(opt_includeInstance) {
  return proto.gameproto.v1.LookAroundAnswer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gameproto.v1.LookAroundAnswer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gameproto.v1.LookAroundAnswer.toObject = function(includeInstance, msg) {
  var f, obj = {
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.gameproto.v1.Object.toObject, includeInstance),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gameproto.v1.LookAroundAnswer}
 */
proto.gameproto.v1.LookAroundAnswer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gameproto.v1.LookAroundAnswer;
  return proto.gameproto.v1.LookAroundAnswer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gameproto.v1.LookAroundAnswer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gameproto.v1.LookAroundAnswer}
 */
proto.gameproto.v1.LookAroundAnswer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gameproto.v1.Object;
      reader.readMessage(value,proto.gameproto.v1.Object.deserializeBinaryFromReader);
      msg.addResults(value);
      break;
    case 2:
      var value = /** @type {!proto.gameproto.v1.Types} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gameproto.v1.LookAroundAnswer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gameproto.v1.LookAroundAnswer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gameproto.v1.LookAroundAnswer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gameproto.v1.LookAroundAnswer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.gameproto.v1.Object.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * repeated Object results = 1;
 * @return {!Array<!proto.gameproto.v1.Object>}
 */
proto.gameproto.v1.LookAroundAnswer.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.gameproto.v1.Object>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gameproto.v1.Object, 1));
};


/**
 * @param {!Array<!proto.gameproto.v1.Object>} value
 * @return {!proto.gameproto.v1.LookAroundAnswer} returns this
*/
proto.gameproto.v1.LookAroundAnswer.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gameproto.v1.Object=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gameproto.v1.Object}
 */
proto.gameproto.v1.LookAroundAnswer.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gameproto.v1.Object, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gameproto.v1.LookAroundAnswer} returns this
 */
proto.gameproto.v1.LookAroundAnswer.prototype.clearResultsList = function() {
  return this.setResultsList([]);
};


/**
 * optional Types type = 2;
 * @return {!proto.gameproto.v1.Types}
 */
proto.gameproto.v1.LookAroundAnswer.prototype.getType = function() {
  return /** @type {!proto.gameproto.v1.Types} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.gameproto.v1.Types} value
 * @return {!proto.gameproto.v1.LookAroundAnswer} returns this
 */
proto.gameproto.v1.LookAroundAnswer.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


