/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gameproto.v1.ObjectAttribute');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gameproto.v1.ObjectAttribute = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gameproto.v1.ObjectAttribute, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gameproto.v1.ObjectAttribute.displayName = 'proto.gameproto.v1.ObjectAttribute';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gameproto.v1.ObjectAttribute.prototype.toObject = function(opt_includeInstance) {
  return proto.gameproto.v1.ObjectAttribute.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gameproto.v1.ObjectAttribute} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gameproto.v1.ObjectAttribute.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: msg.getName(),
    currentvalue: msg.getCurrentvalue(),
    targetvalue: msg.getTargetvalue(),
    ttl: msg.getTtl()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.gameproto.v1.ObjectAttribute} The clone.
 */
proto.gameproto.v1.ObjectAttribute.prototype.cloneMessage = function() {
  return /** @type {!proto.gameproto.v1.ObjectAttribute} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.gameproto.v1.ObjectAttribute.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.gameproto.v1.ObjectAttribute.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string currentvalue = 2;
 * @return {string}
 */
proto.gameproto.v1.ObjectAttribute.prototype.getCurrentvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.gameproto.v1.ObjectAttribute.prototype.setCurrentvalue = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string targetvalue = 3;
 * @return {string}
 */
proto.gameproto.v1.ObjectAttribute.prototype.getTargetvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.gameproto.v1.ObjectAttribute.prototype.setTargetvalue = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 ttl = 4;
 * @return {number}
 */
proto.gameproto.v1.ObjectAttribute.prototype.getTtl = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.gameproto.v1.ObjectAttribute.prototype.setTtl = function(value) {
  jspb.Message.setField(this, 4, value);
};


