/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gameproto.v1.Object');

goog.require('jspb.Message');
goog.require('proto.gameproto.v1.ObjectAttribute');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gameproto.v1.Object = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gameproto.v1.Object.repeatedFields_, null);
};
goog.inherits(proto.gameproto.v1.Object, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gameproto.v1.Object.displayName = 'proto.gameproto.v1.Object';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gameproto.v1.Object.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gameproto.v1.Object.prototype.toObject = function(opt_includeInstance) {
  return proto.gameproto.v1.Object.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gameproto.v1.Object} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gameproto.v1.Object.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: msg.getUuid(),
    x: msg.getX(),
    y: msg.getY(),
    attributesList: jspb.Message.toObjectList(msg.getAttributesList(),
    proto.gameproto.v1.ObjectAttribute.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.gameproto.v1.Object} The clone.
 */
proto.gameproto.v1.Object.prototype.cloneMessage = function() {
  return /** @type {!proto.gameproto.v1.Object} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.gameproto.v1.Object.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.gameproto.v1.Object.prototype.setUuid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 x = 2;
 * @return {number}
 */
proto.gameproto.v1.Object.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.gameproto.v1.Object.prototype.setX = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 y = 3;
 * @return {number}
 */
proto.gameproto.v1.Object.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.gameproto.v1.Object.prototype.setY = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated ObjectAttribute attributes = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.gameproto.v1.ObjectAttribute>}
 */
proto.gameproto.v1.Object.prototype.getAttributesList = function() {
  return /** @type{!Array.<!proto.gameproto.v1.ObjectAttribute>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gameproto.v1.ObjectAttribute, 4));
};


/** @param {Array.<!proto.gameproto.v1.ObjectAttribute>} value  */
proto.gameproto.v1.Object.prototype.setAttributesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


proto.gameproto.v1.Object.prototype.clearAttributesList = function() {
  this.setAttributesList([]);
};


