// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SessionRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_08811059fc349bf8, []int{0}
}
func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (dst *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(dst, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

func (m *SessionRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SessionGrant struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionGrant) Reset()         { *m = SessionGrant{} }
func (m *SessionGrant) String() string { return proto.CompactTextString(m) }
func (*SessionGrant) ProtoMessage()    {}
func (*SessionGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_08811059fc349bf8, []int{1}
}
func (m *SessionGrant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionGrant.Unmarshal(m, b)
}
func (m *SessionGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionGrant.Marshal(b, m, deterministic)
}
func (dst *SessionGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionGrant.Merge(dst, src)
}
func (m *SessionGrant) XXX_Size() int {
	return xxx_messageInfo_SessionGrant.Size(m)
}
func (m *SessionGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionGrant.DiscardUnknown(m)
}

var xxx_messageInfo_SessionGrant proto.InternalMessageInfo

func (m *SessionGrant) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SessionGrant) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type LookAroundRequest struct {
	Myuuid               string   `protobuf:"bytes,1,opt,name=myuuid,proto3" json:"myuuid,omitempty"`
	Otheruuid            string   `protobuf:"bytes,2,opt,name=otheruuid,proto3" json:"otheruuid,omitempty"`
	Tellmemore           bool     `protobuf:"varint,3,opt,name=tellmemore,proto3" json:"tellmemore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookAroundRequest) Reset()         { *m = LookAroundRequest{} }
func (m *LookAroundRequest) String() string { return proto.CompactTextString(m) }
func (*LookAroundRequest) ProtoMessage()    {}
func (*LookAroundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_08811059fc349bf8, []int{2}
}
func (m *LookAroundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookAroundRequest.Unmarshal(m, b)
}
func (m *LookAroundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookAroundRequest.Marshal(b, m, deterministic)
}
func (dst *LookAroundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookAroundRequest.Merge(dst, src)
}
func (m *LookAroundRequest) XXX_Size() int {
	return xxx_messageInfo_LookAroundRequest.Size(m)
}
func (m *LookAroundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookAroundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookAroundRequest proto.InternalMessageInfo

func (m *LookAroundRequest) GetMyuuid() string {
	if m != nil {
		return m.Myuuid
	}
	return ""
}

func (m *LookAroundRequest) GetOtheruuid() string {
	if m != nil {
		return m.Otheruuid
	}
	return ""
}

func (m *LookAroundRequest) GetTellmemore() bool {
	if m != nil {
		return m.Tellmemore
	}
	return false
}

type LookAroundAnswer struct {
	Results              []*Object `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LookAroundAnswer) Reset()         { *m = LookAroundAnswer{} }
func (m *LookAroundAnswer) String() string { return proto.CompactTextString(m) }
func (*LookAroundAnswer) ProtoMessage()    {}
func (*LookAroundAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_08811059fc349bf8, []int{3}
}
func (m *LookAroundAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookAroundAnswer.Unmarshal(m, b)
}
func (m *LookAroundAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookAroundAnswer.Marshal(b, m, deterministic)
}
func (dst *LookAroundAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookAroundAnswer.Merge(dst, src)
}
func (m *LookAroundAnswer) XXX_Size() int {
	return xxx_messageInfo_LookAroundAnswer.Size(m)
}
func (m *LookAroundAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_LookAroundAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_LookAroundAnswer proto.InternalMessageInfo

func (m *LookAroundAnswer) GetResults() []*Object {
	if m != nil {
		return m.Results
	}
	return nil
}

type ObjectAttribute struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Currentvalue         string   `protobuf:"bytes,2,opt,name=currentvalue,proto3" json:"currentvalue,omitempty"`
	Targetvalue          string   `protobuf:"bytes,3,opt,name=targetvalue,proto3" json:"targetvalue,omitempty"`
	Ttl                  int32    `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectAttribute) Reset()         { *m = ObjectAttribute{} }
func (m *ObjectAttribute) String() string { return proto.CompactTextString(m) }
func (*ObjectAttribute) ProtoMessage()    {}
func (*ObjectAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_08811059fc349bf8, []int{4}
}
func (m *ObjectAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectAttribute.Unmarshal(m, b)
}
func (m *ObjectAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectAttribute.Marshal(b, m, deterministic)
}
func (dst *ObjectAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectAttribute.Merge(dst, src)
}
func (m *ObjectAttribute) XXX_Size() int {
	return xxx_messageInfo_ObjectAttribute.Size(m)
}
func (m *ObjectAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectAttribute proto.InternalMessageInfo

func (m *ObjectAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectAttribute) GetCurrentvalue() string {
	if m != nil {
		return m.Currentvalue
	}
	return ""
}

func (m *ObjectAttribute) GetTargetvalue() string {
	if m != nil {
		return m.Targetvalue
	}
	return ""
}

func (m *ObjectAttribute) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type Object struct {
	Uuid                 string             `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	X                    int32              `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32              `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Attributes           []*ObjectAttribute `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_08811059fc349bf8, []int{5}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (dst *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(dst, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Object) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Object) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Object) GetAttributes() []*ObjectAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionRequest)(nil), "gameproto.v1.SessionRequest")
	proto.RegisterType((*SessionGrant)(nil), "gameproto.v1.SessionGrant")
	proto.RegisterType((*LookAroundRequest)(nil), "gameproto.v1.LookAroundRequest")
	proto.RegisterType((*LookAroundAnswer)(nil), "gameproto.v1.LookAroundAnswer")
	proto.RegisterType((*ObjectAttribute)(nil), "gameproto.v1.ObjectAttribute")
	proto.RegisterType((*Object)(nil), "gameproto.v1.Object")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SessionClient is the client API for Session service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionClient interface {
	NewSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionGrant, error)
	LookAround(ctx context.Context, opts ...grpc.CallOption) (Session_LookAroundClient, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) NewSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionGrant, error) {
	out := new(SessionGrant)
	err := c.cc.Invoke(ctx, "/gameproto.v1.Session/NewSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) LookAround(ctx context.Context, opts ...grpc.CallOption) (Session_LookAroundClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Session_serviceDesc.Streams[0], "/gameproto.v1.Session/LookAround", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionLookAroundClient{stream}
	return x, nil
}

type Session_LookAroundClient interface {
	Send(*LookAroundRequest) error
	Recv() (*LookAroundAnswer, error)
	grpc.ClientStream
}

type sessionLookAroundClient struct {
	grpc.ClientStream
}

func (x *sessionLookAroundClient) Send(m *LookAroundRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sessionLookAroundClient) Recv() (*LookAroundAnswer, error) {
	m := new(LookAroundAnswer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SessionServer is the server API for Session service.
type SessionServer interface {
	NewSession(context.Context, *SessionRequest) (*SessionGrant, error)
	LookAround(Session_LookAroundServer) error
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_NewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).NewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gameproto.v1.Session/NewSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).NewSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_LookAround_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SessionServer).LookAround(&sessionLookAroundServer{stream})
}

type Session_LookAroundServer interface {
	Send(*LookAroundAnswer) error
	Recv() (*LookAroundRequest, error)
	grpc.ServerStream
}

type sessionLookAroundServer struct {
	grpc.ServerStream
}

func (x *sessionLookAroundServer) Send(m *LookAroundAnswer) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sessionLookAroundServer) Recv() (*LookAroundRequest, error) {
	m := new(LookAroundRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gameproto.v1.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewSession",
			Handler:    _Session_NewSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LookAround",
			Handler:       _Session_LookAround_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "game.proto",
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_game_08811059fc349bf8) }

var fileDescriptor_game_08811059fc349bf8 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0xd5, 0xe2, 0xd8, 0xb9, 0x9b, 0xb3, 0xe0, 0x58, 0xa1, 0x93, 0x65, 0x85, 0x60, 0xb9, 0x72,
	0x65, 0x41, 0xe8, 0x90, 0x28, 0x92, 0x02, 0x28, 0x10, 0x88, 0xa5, 0xa3, 0xdb, 0x24, 0xa3, 0x60,
	0xb0, 0xbd, 0x61, 0x3f, 0xe2, 0xa4, 0xe0, 0xdf, 0xf0, 0x43, 0x91, 0xd7, 0xeb, 0xc4, 0x16, 0xa1,
	0xda, 0x79, 0x33, 0x6f, 0xdf, 0x7c, 0x02, 0xec, 0x78, 0x85, 0xf9, 0x5e, 0x0a, 0x2d, 0x68, 0xd8,
	0xda, 0xd6, 0xcc, 0x0f, 0xaf, 0xd2, 0x0f, 0xf0, 0xf8, 0x2b, 0x2a, 0x55, 0x88, 0x9a, 0xe1, 0x2f,
	0x83, 0x4a, 0xd3, 0x18, 0x6e, 0x8c, 0x42, 0x59, 0xf3, 0x0a, 0x23, 0x92, 0x90, 0xec, 0x96, 0x9d,
	0x71, 0x1b, 0xdb, 0x73, 0xa5, 0x1a, 0x21, 0xb7, 0xd1, 0xa3, 0x2e, 0xd6, 0xe3, 0xf4, 0x0d, 0x84,
	0x4e, 0xe9, 0xbd, 0xe4, 0xb5, 0xa6, 0x14, 0x26, 0xc6, 0x14, 0x5b, 0xa7, 0x61, 0x6d, 0xfa, 0x00,
	0x81, 0x44, 0xae, 0x44, 0xed, 0x7e, 0x3b, 0x94, 0x16, 0xf0, 0xf4, 0xa3, 0x10, 0x3f, 0x97, 0x52,
	0x98, 0x7a, 0xdb, 0x17, 0xf2, 0x00, 0x41, 0x75, 0x1a, 0x48, 0x38, 0x44, 0x67, 0x70, 0x2b, 0xf4,
	0x77, 0x94, 0x36, 0xd4, 0xe9, 0x5c, 0x1c, 0x74, 0x0e, 0xa0, 0xb1, 0x2c, 0x2b, 0xac, 0x84, 0xc4,
	0xc8, 0x4b, 0x48, 0x76, 0xc3, 0x06, 0x9e, 0x74, 0x05, 0xf7, 0x97, 0x54, 0xcb, 0x5a, 0x35, 0x28,
	0x69, 0x0e, 0x53, 0x89, 0xca, 0x94, 0x5a, 0x45, 0x24, 0xf1, 0xb2, 0xbb, 0xc5, 0xb3, 0x7c, 0x38,
	0xa4, 0xfc, 0xf3, 0xfa, 0x07, 0x6e, 0x34, 0xeb, 0x49, 0xe9, 0x6f, 0x78, 0xd2, 0xb9, 0x96, 0x5a,
	0xcb, 0x62, 0x6d, 0x34, 0xb6, 0xdd, 0x0e, 0x26, 0x66, 0x6d, 0x9a, 0x42, 0xb8, 0x31, 0x52, 0x62,
	0xad, 0x0f, 0xbc, 0x34, 0xe8, 0x6a, 0x1d, 0xf9, 0x68, 0x02, 0x77, 0x9a, 0xcb, 0x1d, 0x3a, 0x8a,
	0x67, 0x29, 0x43, 0x17, 0xbd, 0x07, 0x4f, 0xeb, 0x32, 0x9a, 0x24, 0x24, 0xf3, 0x59, 0x6b, 0xa6,
	0x0d, 0x04, 0x5d, 0xfa, 0xab, 0x33, 0x0e, 0x81, 0x1c, 0x6d, 0x2a, 0x9f, 0x91, 0x63, 0x8b, 0x4e,
	0x56, 0xd5, 0x67, 0xe4, 0x44, 0xdf, 0x02, 0xf0, 0xbe, 0x64, 0x15, 0x4d, 0x6c, 0xaf, 0xcf, 0xaf,
	0xf5, 0x7a, 0x6e, 0x8c, 0x0d, 0x3e, 0x2c, 0xfe, 0x10, 0x98, 0xba, 0x1d, 0xd3, 0x77, 0x00, 0x9f,
	0xb0, 0xe9, 0xd1, 0x6c, 0x2c, 0x32, 0x3e, 0xa9, 0x38, 0xbe, 0x1a, 0xed, 0xce, 0xe4, 0x0b, 0xc0,
	0x65, 0x1f, 0xf4, 0xc5, 0x98, 0xf9, 0xcf, 0x51, 0xc4, 0xf3, 0xff, 0x11, 0xba, 0x55, 0x66, 0xe4,
	0x25, 0x59, 0x4d, 0xbf, 0xf9, 0x96, 0xb0, 0x0e, 0xec, 0xf3, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0xa6, 0x07, 0xcc, 0xff, 0x02, 0x00, 0x00,
}
